PRO/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('api/',include('api.urls')),
    path('',include('control.urls',namespace='control')),

    path('',include('products.urls',namespace='products')),
    path('order/',include('order.urls',namespace='order')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path ,include
from . import views

app_name='employees'

urlpatterns = [
        path('', views.employees, name='employees'),
        path('/<int:id>',views.delete_employee,name='delete_employee'),  
        # path('signup', views.signup, name='signup'),
        path('profile/', views.employe, name='employe'),

        path('profile/<int:id>', views.employee, name='employee'),

        path('employee_edit', views.employee_edit, name='employee_edit'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "proImage/%s.%s"%(instance.id,extension)


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    fname = models.CharField(max_length=20)
    lname = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    image = models.ImageField(upload_to=image_upload,default='photo.jpg')
    def __str__(self):
        return str(self.user)

    
## create new user ---> create new empty profile

@receiver(post_save, sender=User)
def create_user_profile(sender,instance, created ,**kwargs):
    if created:
        Employee.objects.create(user=instance)
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Employee

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password1','password2',]


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = '__all__'
        exclude = ('user','photo')

accounts/views.py
from django.contrib.auth import authenticate, login
from django.core.checks import messages
from django.shortcuts import redirect, render
from .forms import SignupForm ,EmployeeForm ,UserForm
from .models import Employee
from django.urls import reverse
from django.core.paginator import Paginator
from .filters import EmployeeFilter
# Create your views here.

# def signup(request):
#     if request.method == 'POST':
#         form = SignupForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data['username']
#             password = form.cleaned_data['password1']
#             user = authenticate(username='username', password='password')
#             return redirect('accounts:signup')
#     else:
#         form = SignupForm()
#     return render(request,'accounts/profile_list.html',{'form':form})



def employee(request,id):
    emp = Employee.objects.get(id = id)
    return render(request, 'accounts/employee.html',{'emp':emp})

def employe(request):
    emp = Employee.objects.get(user=request.user)
    return render(request, 'accounts/employee.html',{'emp':emp})


def employee_edit(request):
    emp = Employee.objects.get(user=request.user)
    if request.method=='POST':
        userform = UserForm(request.POST,instance=request.user)
        employeeform= EmployeeForm(request.POST,request.FILES, instance=emp)
        if userform.is_valid() and employeeform.is_valid():
            userform.save()
            employeeform = employeeform.save(commit=False)
            employeeform.user = request.user
            employeeform.save() 
            return redirect(reverse('accounts:employee',kwargs={"id":emp.id}))
    else:
        userform = UserForm(instance=request.user)
        employeeform = EmployeeForm(instance=emp)
    return render(request, 'accounts/profile_edit.html',{'userform':userform , 'employeeform':employeeform})    


def employees(request):
    employees = Employee.objects.all()
    #filters
    myfilter = EmployeeFilter(request.GET,queryset=employees)
    employees = myfilter.qs 

    paginator = Paginator(employees,7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # add employee
    if request.method == 'POST':
        empform = SignupForm(request.POST)
        if empform.is_valid():
            empform.save()
            username = empform.cleaned_data['username']
            password = empform.cleaned_data['password1']
            user = authenticate(username='username', password='password')
            return redirect('accounts:employees')
    else:
        empform = SignupForm()
    ################################################3
    context = {'employees':page_obj , 'myfilter':myfilter,'empform':empform}
    return render(request,'accounts/profile_list.html',context)


def delete_employee(request , id):
    employee = Employee.objects.get(id = id)
    employee.delete()

    return redirect(reverse('accounts:employees'))

accounts/templates/accounts/employee.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
    
                <div class="col-lg-8 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{emp.fname}} {{emp.lname}}</span></li>
                                <li>username: <span>{{emp.user}} </span></li>
                                <li>Phone: <span>{{emp.phone}}</span></li>
                                <li>Address: <span>{{emp.city}}</span></li>
                            </ul>
                        </div>
                        {% if emp.user.id == request.user.id %}
                        <div class="p-5boxed-btn3 w-100">
                            <a href="{% url 'accounts:employee_edit' %}" class="boxed-btn3 w-100">Edit Profile</a>
                            <a style="margin-top:10px" href="{% url 'password_change' %}" class="boxed-btn3 w-100">Edit Password</a>
                        </div>
                        {% endif %}
                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock body %}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">

        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit Porfile</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form userform %} 
                            {% bootstrap_form employeeform %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Save</button>
                            {% endbuttons %}     
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

accounts/templates/accounts/profile_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Shop App</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding mx-auto ">
        <div class="container">
            <div class="row ">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method = "GET">

                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-6 ">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6 ">
                                    <h4>Employees List</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for acc in employees %}
                            {% if acc.user.is_superuser %}

                            {% else %}
                            <div class="col-lg-12 col-md-12">
                                <div style="padding:50px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="">
                                            <img src="{{acc.image.url}}"  width=100px style="margin-right:20px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'accounts:employee' acc.id %}"><h4>{{acc.user}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class=""></i>{{acc.phone}}</p>
                                                </div>                              
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="jobs_right">
                                        <div class="apply_now">

                                                {% comment %} <a href="" class="boxed-btn3">Edit</a> {% endcomment %}

                                            <a class="boxed-btn3"  href="{% url 'accounts:delete_employee' acc.id %}">Delete</a>

                                        </div>

                                        {% comment %} <div class="date">
                                            <p>Date Line: </p>
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                         {% endfor %}
                         
                    
                        </div>

                        
                        {% if employees.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if employees.has_previous %}
                                            <li><a href="?page={{employees.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in employees.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if employees.has_next %}
                                            <li><a href="?page={{employees.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    

                </div>
                <div class="col-lg-3 job_details_area container " style="padding-top:0px">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Add Employee</h3>
                        </div>
                        <div class="job_content">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form empform %} 
                                {% buttons %}
                                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}     
    
                            </form>
                        </div>
                    </div>
                    
                </div>

            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}