PRO/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('api/',include('api.urls')),
    path('',include('control.urls',namespace='control')),

    path('',include('products.urls',namespace='products')),
    path('order/',include('order.urls',namespace='order')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('',views.order,name="order"),
    path('<int:id>',views.order_details,name="order_details"),
    path('/<int:id>',views.order_wait,name="order_wait"),
    path('//<int:id>',views.make_order_done,name='make_order_done'),  
    path('/<int:id>/',views.order_back,name='order_back'),  
    path('/old-order',views.order_done,name='order_done'),  
    path('/old-order/',views.order_done_delete,name='order_done_delete'),  


]
    

order/models.py
from django.db import models
from products.models import Products
from django.contrib.auth.models import User

# from django.contrib.postgres.fields import ArrayField

# # Create your models here.
def all_products():
    product = Products.objects.all()
    return product

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "proImage/%s.%s"%(instance.id,extension)

class Order(models.Model):
    user = models.CharField(max_length=50,default='admin')

    name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=100)
    published_at = models.DateTimeField(auto_now=True)
    id_products = models.IntegerField(default=4)
    products = models.ManyToManyField(Products,blank=True,null=True,default=all_products)
    quantity = models.IntegerField(default=1)
    receive = models.IntegerField(default=1)
    done = models.IntegerField(default=2)
    image = models.ImageField(upload_to=image_upload,default='photo.jpg')
    locx = models.FloatField()
    locy = models.FloatField()

    # location = models.ManyToManyField(Location)
    def __str__(self):
        return self.name
# class Odder_details(models.Model):
#     pass

order/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .models import Order
from .form import ProductForm
from .filters import OrderFilter
from django.core.paginator import Paginator

# Create your views here.


def order(request):
    orders = Order.objects.all()

    if request.method == 'POST':
        proform = ProductForm(request.POST, request.FILES)
        if proform.is_valid():
            proform.save()
            return redirect(reverse('order:order'))
    else:
        proform = ProductForm()

    context = { 'orders':orders, 'proform':proform}
    return render(request,'order/order_list.html',context)


def order_details(request,id):
    orders = Order.objects.get(id=id)
    order = orders.products.all()
    # orders.products.id = orders.id_products
    context = { 'orders':orders ,'order':order} 
    return render(request,'order/order_details.html',context)

def order_wait(request,id):

    order_wait=Order.objects.get(id=id)
    order_wait.receive = 2
    order_wait.user = request.user.username
    order_wait.save()

    return redirect(reverse('order:order'))

def make_order_done(request,id):

    order_done=Order.objects.get(id=id)
    order_done.done = 1
    order_done.save()

    return redirect(reverse('order:order'))

def order_done(request):
    order_done = Order.objects.all()
    #filters
    myfilter = OrderFilter(request.GET,queryset=order_done)
    order_done = myfilter.qs 

    paginator = Paginator(order_done,7)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'order_done':page_obj , 'myfilter':myfilter }
    return render(request,'order/order_done.html',context)

def order_done_delete(request):
    order_done = Order.objects.all()
    for order in order_done:
        if order.done == 1:
            order.delete()
    return redirect(reverse('order:order_done'))


def order_back(request,id):

    order_back=Order.objects.get(id=id)
    order_back.receive = 1
    order_back.user = 'admin'
    order_back.save()

    return redirect(reverse('order:order'))

order/templates/order/order_details.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3></h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="">
                                    <img src="{{orders.image.url}}"  width=100px style="margin-right:20px" alt="">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{orders.name}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">

                                        <div class="location">
                                            <p> <i class=""></i>{{orders.address}}</p>
                                        </div>

                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="" style="">
                                    <div class="apply_now " style="padding-top:5px "  >
                                        <a class="boxed-btn3" style="font-size:18px;" href="{% url 'order:make_order_done' orders.id%}" style="margin:5px; width:10%">تم</a>
                                        <a class="boxed-btn3" style="font-size:18px" href="{% url 'order:order_back' orders.id%}">تراجع</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h1>Product</h1>

                            {% comment %} <div class="location">
                                <p> <i class=""></i>{{ord.title}} : {{ord.price}} ل.س</p>
                            </div> {% endcomment %}

                            <div class="jobs_left d-flex align-items-center row"style="margin-bottom:30px">

                                {% for ord in order %}

                           {% if ord.id == orders.id_products %}

                                    <div class="">
                                        <img src="{{ord.image.url}}"  width=200px style="margin:10px" alt="">
                                    </div>

                                    <div class="jobs_conetent " style="margin-right:50px">
                                        <a href=""><h2 style="margin-top:-50px">{{ord.title}}</h2></a>
                                        <div class="links_locat d-flex align-items-center">
                                            <div class="location">
                                                <p style="margin-top:40px; font-size:18px"> <i class=""></i>سعر القطعة: {{ord.price}} ل.س</p>
                                                <p style="font-size:18px;margin-left:100px"> <i class=""></i>الكمية: {{orders.quantity}}</p>
                                            </div>        
                      
                                        </div>
                                    </div>
                                    {% endif %}
                                {% endfor %}
                            </div>

                            <p></p>
                        </div>
   
                    </div>
                    {% comment %} <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}     

                        </form>
                    </div> {% endcomment %}
                </div>
                <div class="col-lg-4">
                    {% comment %} <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}} Position</span></li>
                                <li>Salary: <span>{{job.salary}}</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span>{{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div> {% endcomment %}
                    {% comment %} <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div> {% endcomment %}
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 338px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: { lat: {{orders.locx}}, lng : {{orders.locy}}},
                                  zoom: 15,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });

                                var marker = new google.maps.Marker({
                                    position:{ lat: {{orders.locx}}, lng : {{orders.locy}}},
                                    title: 'cust',
                                    map : map,
                                })
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                             
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

order/templates/order/order_done.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Shop App</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding mx-auto ">
        <div class="container">
            <div class="row ">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method = "GET">

                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-7 ">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6 ">
                                    <h4>Order List</h4>
                                </div>
                                <div style="margin=0px; padding=0px" class=" ">
                                    <a style="margin-left:200px; " href="{% url 'order:order_done_delete' %}" class="boxed-btn3">Delete</a>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row" >
                        {% for ord in order_done %}
                        
                        {% if ord.done == 1 %}
                            <div class="col-lg-12 col-md-12">
                                <div style="padding:50px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="">
                                            <img src="{{ord.image.url}}"  width=100px style="margin-right:20px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'order:order_details' ord.id %}"><h4>{{ord.name}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class=""></i>{{ord.address}}</p>
                                                </div>                              
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                        
                                            <p class="brn brn-outline-primary"  >{{ord.user}} تم التسليم من قبل</p>

                                            <div class="date">
                                                <p>{{ord.published_at}}</p>
                                            </div>
                                        </div>

                                        {% comment %} <div class="date">
                                            <p>Date Line: </p>
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                         {% endfor %}

                    
                        </div>

                        
                        {% if order_done.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if order_done.has_previous %}
                                            <li><a href="?page={{order_done.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in order_done.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if order_done.has_next %}
                                            <li><a href="?page={{order_done.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    

                </div>
                {% comment %} <div class="col-lg-5 job_details_area container"style="padding-top:0px" >
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Add Product</h3>
                        </div>
                        <div class="job_content">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form proform %} 
                                {% buttons %}
                                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}     
    
                            </form>
                        </div>
                    </div>
                    
                </div> {% endcomment %}

            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

order/templates/order/order_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Shop App</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- bradcam_area -->

    <!--- job_listing_area_start  -->
    <div class="job_listing_area plus_padding mx-auto ">
        <div class="container">
            <div class="row ">
                {% comment %} <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method = "GET">

                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div> {% endcomment %}
                <div class="col-lg-7 ">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6 ">
                                    <h4>Order List</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row" >
                        {% for ord in orders %}
                        {% if ord.receive == 1 %}
                            <div class="col-lg-12 col-md-12">
                                <div style="padding:50px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="">
                                            <img src="{{ord.image.url}}"  width=100px style="margin-right:20px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'order:order_details' ord.id %}"><h4>{{ord.name}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class=""></i>{{ord.address}}</p>
                                                </div>                              
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="jobs_right">
                                        <div class="apply_now">

                                                <a class="boxed-btn3 w-100" style="font-size:18px"  href="{% url 'order:order_wait' ord.id%}">استلام</a>

                                        </div>

                                        <div class="date">
                                            <p>{{ord.published_at}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>


{% elif ord.receive == 2 and request.user.is_superuser or ord.user == request.user.username%}
                        {% if ord.done == 2 %}
                            <div class="col-lg-12 col-md-12">
                                <div style="padding:50px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="">
                                            <img src="{{ord.image.url}}"  width=100px style="margin-right:20px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'order:order_details' ord.id %}"><h4>{{ord.name}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class=""></i>{{ord.address}}</p>
                                                </div>                              
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            {% if ord.user == request.user.username and ord.receive == 2 %}
                                                <a class="boxed-btn3" style="font-size:18px;" href="{% url 'order:make_order_done' ord.id%}" style="margin:5px; width:10%">تم</a>
                                                <a class="boxed-btn3" style="font-size:18px" href="{% url 'order:order_back' ord.id%}">تراجع</a>

                                            {% elif request.user.is_superuser and ord.receive == 2%}
                                                <p class="brn brn-outline-primary"  >{{ord.user}} قيد التسليم من قبل</p>
                                            {% else %}
                                                <a class="boxed-btn3 w-100"  href="{% url 'order:order_wait' ord.id%}">استلام</a>

                                            {% endif %}

                                            <div class="date">
                                                <p>{{ord.published_at}}</p>
                                            </div>
                                        </div>

                                        {% comment %} <div class="date">
                                            <p>Date Line: </p>
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                        {% endif %}
                         {% endfor %}

                    
                        </div>

                        
                        {% comment %} {% if employees.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if employees.has_previous %}
                                            <li><a href="?page={{employees.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in employees.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}


{% if employees.has_next %}
                                            <li><a href="?page={{employees.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %} {% endcomment %}
                    </div>
                    

                </div>
                <div class="col-lg-5 job_details_area container"style="padding-top:0px" >
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Add Product</h3>
                        </div>
                        <div class="job_content">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form proform %} 
                                {% buttons %}
                                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}     
    
                            </form>
                        </div>
                    </div>
                    
                </div>

            </div>
        </div>
    </div>
    <!— job_listing_area_end  —>
{% endblock body %}