PRO/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('api/',include('api.urls')),
    path('',include('control.urls',namespace='control')),

    path('',include('products.urls',namespace='products')),
    path('order/',include('order.urls',namespace='order')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path ,include
from . import views

app_name='employees'

urlpatterns = [
        path('', views.employees, name='employees'),
        path('/<int:id>',views.delete_employee,name='delete_employee'),  
        # path('signup', views.signup, name='signup'),
        path('profile/', views.employe, name='employe'),

        path('profile/<int:id>', views.employee, name='employee'),

        path('employee_edit', views.employee_edit, name='employee_edit'),
]

api/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.apiAll,name="apiAll"),
    
    path('products/',views.productsList,name="products"),
    path('order/',views.orderList,name="order"),
    path('create_order/',views.orderCreate.as_view(),name="create_order"),

    path('products_delail/<str:pk>/',views.productsDelail,name="products_delail"),

    path('create_products/',views.productsCreate.as_view(),name="create_products"),

    path('update_products/<str:pk>/',views.productsUpdate,name="update_products"),

    path('delete_products/<str:pk>/',views.productsDelete,name="delete_products"),
]

order/urls.py
from django.urls import path
from . import views
app_name = 'order'
urlpatterns = [
    path('',views.order,name="order"),
    path('<int:id>',views.order_details,name="order_details"),
    path('/<int:id>',views.order_wait,name="order_wait"),
    path('//<int:id>',views.make_order_done,name='make_order_done'),  
    path('/<int:id>/',views.order_back,name='order_back'),  
    path('/old-order',views.order_done,name='order_done'),  
    path('/old-order/',views.order_done_delete,name='order_done_delete'),  


]
    

products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('products',views.products,name="products"),
    path('pause_pro/<int:id>',views.product_hide,name="product_hide"),
    path('pause_pro',views.pause_products,name="pause_products"),
    path('pause_pro/<int:id>/',views.delete_pause_product,name='delete_pause_product'),  
    path('<int:id>/',views.delete_product,name='delete_product'),  
    path('<int:id>',views.product_details,name='product_details'),    
    path('edir_pro/<int:id>',views.update_product,name='update_product'),  
    
]
    

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Shop App</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{%static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/magnific-popup.css'%}">
    <link rel="stylesheet" href="{%static 'css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/themify-icons.css'%}">
    <link rel="stylesheet" href="{%static 'css/nice-select.css'%}">
    <link rel="stylesheet" href="{%static 'css/flaticon.css'%}">
    <link rel="stylesheet" href="{%static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{%static 'css/gijgo.css'%}">
    <link rel="stylesheet" href="{%static 'css/animate.min.css'%}">
    <link rel="stylesheet" href="{%static 'css/slicknav.css'%}">

    <link rel="stylesheet" href="{%static 'css/stylee.css'%}">
    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
    
</head>

<body >
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        {% if request.user.is_superuser %}
                                            <ul id="navigation">
                                                <li><a href="{% url 'products:products' %}"><strong>Home</strong></a></li>
                                                <li><a href="{% url 'products:pause_products' %}"><strong>Pause Products</strong></a></li>
                                                <li><a href="{% url 'accounts:employees' %}"><strong>Employees</strong> <i class=""></i></a></li>
                                                <li><a href="{% url 'order:order' %}"><strong>Orders</strong></a></li>
                                                <li><a href="{% url 'order:order_done' %}"><strong>Old Orders</strong></a></li>
                                            </ul>
                                        {% endif %}
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-5 d-none d-lg-block">
                                    <div class="col-xl-10 col-lg-7">
                                        <div class="main-menu  d-none d-lg-block">
                                            <nav>
                                                {% if request.user.is_superuser %}
                                                    <a  class="boxed-btn3" href=" {% url 'logout' %} ">Log out</a>
                                                {% elif request.user.is_authenticated %}
                                                    <ul id="navigation">
                                                        <li><a class="btn btn-dark" href="#">My Account <i class="ti-angle-down"></i></a>
                                                        <ul class="submenu">
                                                        <li><a href="{% url 'order:order' %}">Home</a></li>
                                                        <li><a href="{% url 'accounts:employe'  %}">My Profile </a></li>
                                                        <li><a href=" {% url 'logout' %} ">Log out</a></li>
                                                        </ul>
                                                        </li> 
                                                    </ul>
                                                {% endif %}
                                            </nav>
                                        </div>
                                    </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

    {% block body %}
    
    {% endblock body %}

    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="img/logo.png" alt="">
                                </a>
                            </div>
                            <p>
                                +963993178291<br>
                                +963936553805<br>
                                +963991313929<br>
                                
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
<!-- JS here -->
    <script src="{%static 'js/vendor/modernizr-3.5.0.min.js'%}"></script>
    <script src="{%static 'js/vendor/jquery-1.12.4.min.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
    <script src="{%static 'js/owl.carousel.min.js'%}"></script>
    <script src="{%static 'js/isotope.pkgd.min.js'%}"></script>
    <script src="{%static 'js/ajax-form.js'%}"></script>
    <script src="{%static 'js/waypoints.min.js'%}"></script>
    <script src="{%static 'js/jquery.counterup.min.js'%}"></script>
    <script src="{%static 'js/imagesloaded.pkgd.min.js'%}"></script>
    <script src="{%static 'js/scrollIt.js'%}"></script>
    <script src="{%static 'js/jquery.scrollUp.min.js'%}"></script>
    <script src="{%static 'js/wow.min.js'%}"></script>
    <script src="{%static 'js/nice-select.min.js'%}"></script>
    <script src="{%static 'js/jquery.slicknav.min.js'%}"></script>
    <script src="{%static 'js/jquery.magnific-popup.min.js'%}"></script>
    <script src="{%static 'js/plugins.js'%}"></script>
    <!-- <script src="{%static 'js/gijgo.min.js'%}"></script> -->
    <script src="{%static 'js/range.js'%}"></script>



    <!--contact js-->
    <script src="{%static 'js/contact.js'%}"></script>
    <script src="{%static 'js/jquery.ajaxchimp.min.js'%}"></script>
    <script src="{%static 'js/jquery.form.js'%}"></script>
    <script src="{%static 'js/jquery.validate.min.js'%}"></script>
    <script src="{%static 'js/mail-script.js'%}"></script>


    <script src="{%static 'js/main.js'%}"></script>


	<script>
        
        $( function() {
            $( "#slider-range" ).slider({
                range: true,
                min: 0,
                max: 24600,
                values: [ 750, 24600 ],
                slide: function( event, ui ) {
                    $( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] +"/ Year" );
                }
            });
            $( "#amount" ).val( "$" + $( "#slider-range" ).slider( "values", 0 ) +
                " - $" + $( "#slider-range" ).slider( "values", 1 ) + "/ Year");
        } );
        </script>
</body>

</html>     

templates/base_generic.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">

    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        {% block content %}
                        
                        {% endblock content %}

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}