PRO/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),

    path('api/',include('api.urls')),
    path('',include('control.urls',namespace='control')),

    path('',include('products.urls',namespace='products')),
    path('order/',include('order.urls',namespace='order')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from . import views
app_name = 'products'
urlpatterns = [
    path('products',views.products,name="products"),
    path('pause_pro/<int:id>',views.product_hide,name="product_hide"),
    path('pause_pro',views.pause_products,name="pause_products"),
    path('pause_pro/<int:id>/',views.delete_pause_product,name='delete_pause_product'),  
    path('<int:id>/',views.delete_product,name='delete_product'),  
    path('<int:id>',views.product_details,name='product_details'),    
    path('edir_pro/<int:id>',views.update_product,name='update_product'),  
    
]
    

products/models.py
from django.db import models
from djongo import models

# Create your models here.

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "proImage/%s.%s"%(instance,extension)

class Products(models.Model):
    title = models.CharField(max_length=50)
    price = models.IntegerField()
    description = models.TextField(max_length=1000)
    description2 = models.TextField(max_length=1000, blank=True, null=True )
    image = models.ImageField(upload_to=image_upload)
    hide = models.BooleanField(default=False)
    def __str__(self):
        return self.title


# class ArrayField(MongoField):
#         def __init__(self,
#                     model_container: typing.Type[Model],
#                     model_form_class: typing.Type[forms.ModelForm] = None,
#                     model_form_kwargs: dict = None,
#                     *args, **kwargs):

products/views.py
from django.shortcuts import redirect, render
from django.core.paginator import Paginator
from django.urls import reverse
from .models import Products
from .filters import ProdactFilter
from django.contrib.auth.decorators import login_required
from .form import ProductForm
# Create your views here.

@login_required

def products(request):
    products = Products.objects.all()
    #filters
    myfilter = ProdactFilter(request.GET,queryset=products)
    products = myfilter.qs 

    paginator = Paginator(products,9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    # add product
    if request.method == 'POST':
        proform = ProductForm(request.POST, request.FILES)
        if proform.is_valid():
            proform.save()
            return redirect(reverse('products:products'))
    else:
        proform = ProductForm()
    ################################################3
    context = {'products':page_obj , 'myfilter':myfilter , 'proform':proform}
    return render(request,'products/pro_list.html',context)


def product_details(request,id):
    product_details=Products.objects.get(id=id)

    context={'products':product_details}
    return render(request,'products/pro_details.html',context)


def update_product(request , id):
    product = Products.objects.get(id = id)
    if request.method =='POST':
        form = ProductForm(request.POST , request.FILES , instance = product)
        if form.is_valid():
            form.save()
            return redirect('products:product_details',id)
    else:
        form = ProductForm(instance = product)
    context = {'form' : form}
    return render(request,'products/edit_pro.html',context)


def delete_product(request , id):
    product = Products.objects.get(id = id)
    product.delete()

    return redirect(reverse('products:products'))

def delete_pause_product(request , id):
    product = Products.objects.get(id = id)
    product.delete()

    return redirect(reverse('products:pause_products'))

def product_hide(request,id):
    product_hide=Products.objects.get(id=id)
    product_hide.hide = True
    product_hide.save()

    return redirect(reverse('products:pause_products'))


#  pause products

def pause_products(request):
    products = Products.objects.all()
    #filters
    myfilter = ProdactFilter(request.GET,queryset=products)
    products = myfilter.qs 

    paginator = Paginator(products,1000)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'products':page_obj , 'myfilter':myfilter}
    return render(request,'products/pause_pro_list.html',context)

products/templates/products/edit_pro.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Edit product </h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area plus_padding">
        <div class="container ">
            <div class="row ">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4>Edit product</h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %} 
                            {% buttons %}
                                 <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}     

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

products/templates/products/pause_pro_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Shop App</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding mx-auto ">
        <div class="container">
            <div class="row ">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method = "GET">

                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-9 ">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6 ">
                                    <h4>Products</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        {% for pro in products %}
                            {% if pro.hide == False %}
                            <div class="col-lg-12 col-md-12">
                                <div style="padding:50px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="">
                                            <img src="{{pro.image.url}}"  width=100px style="margin-right:10px" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'products:product_details' pro.id %}"><h4>{{pro.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class=""></i>Price: {{pro.price}} S.B</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="" style="margin:-10px">
                                        <div class="apply_now" style="padding-bottom:5px; ">
                                            <a href="{% url 'products:product_hide' pro.id %}" class="boxed-btn3" style="width:197px;" >Accept</a>
                                        </div>
                                        <div class="apply_now" style="padding-top:5px padding-bottom:5px">
                                            <a class="brn brn-outline-primary boxed-btn3"  href="{% url 'products:delete_pause_product' pro.id %}">Delete</a>
                                            <a href="{% url 'products:update_product' pro.id %}" class="boxed-btn3">Edit</a>
                                        </div>
                                        {% comment %} <div class="date">
                                            <p>Date Line: </p>
                                        </div> {% endcomment %}
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                         {% endfor %}

                    
                        </div>

                        
                        {% if products.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if products.has_previous %}
                                            <li><a href="?page={{products.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in products.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if products.has_next %}
                                            <li><a href="?page={{products.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                    

                </div>
                {% comment %} <div class="col-lg-3 job_details_area container ">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Add Product</h3>
                        </div>
                        <div class="job_content">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form proform %} 
                                {% buttons %}
                                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}     
    
                            </form>
                        </div>
                    </div>
                    
                </div> {% endcomment %}

            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}

products/templates/products/pro_details.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{products}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area mx-auto" >
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">

                                    <img src="{{products.image.url}}" , width=100px style="margin-right:10px" alt="">
                              
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{products.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
    
                                        <div class="location">
                                            <p> <i class=""></i> {{products.price}} S.B</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="" style="">
                                    <div class="apply_now " style="padding-top:5px "  >
                                        <a href="{% url 'products:update_product' products.id %}" class="boxed-btn3">Edit</a>
                                        <a class="brn brn-outline-primary boxed-btn3"  href="{% url 'products:delete_product' products.id %}">Delete</a>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Product Title</h4>
                            <p>{{products.description2}}</p>
                        </div>
   
                        <div class="single_wrap">
                            <h4>Product Description</h4>
                            <p>{{products.description}}</p>
                        </div>
   
                    </div>

                </div>
                
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

products/templates/products/pro_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Shop App</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->

    <div class="pos-f-t job_listing_area">
        <nav class="navbar navbar-dark">
            <button class="navbar-toggler boxed-btn3 " type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
             <span  class="navbar-toggler-icon" style="margin-left:-10px;"></span><span style="margin-left:10px;font-size:18px;">Add Product</span>
            </button>
          </nav>
        <div class="collapse" id="navbarToggleExternalContent">
          <div class="p-4">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form proform %} 
                {% buttons %}
                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                {% endbuttons %}     
            </form>
          </div>
        </div>

    </div>
    <div class="job_listing_area plus_padding mx-auto"  style="margin-top:0px; padding-top:0px">
        


        <div class="container">
            <div class="row ">
                <div class="col-lg-3" style="margin-bottom:0px;">
                    <div class="job_filter white-bg" style="margin-bottom:0px;padding-bottom:10px">
                        <div class="form_inner white-bg" style="margin-bottom:00px;padding-bottom:10px">
                            <h3>Filter</h3>
                            <form method = "GET">

                                {% bootstrap_form myfilter.form %} 
                                <input type = "submit" value = "Sreath" class = "boxed-btn3 w-100 mt-2">
                            </form>
                        </div>


                    </div>
                </div>
                <div class="col-lg-9 ">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg" style="width:738px">
                            <div class="row align-items-center">
                                <div class="col-md-5 ">
                                    <h4>Products</h4>
                                </div>

                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0" style="padding-top:0px">
                        <div class="row">
                        {% for pro in products %}
                            {% if pro.hide == True %}
                            <div class="col-lg-5 col-md-5" style="margin-right:-100px;">
                                <div style="margin-right:100px;height:375px" class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center" style="margin-top: -100px;">
                                       
                                        <div class="jobs_conetent" style ="margin-top :40px;margin-left:-30px">
                                            <a href="{% url 'products:product_details' pro.id %}"><h3 class ="ctr_h" style = "text-align:left ; padding-top :0px; ">{{pro.title}} </h3> <p style="margin-left:-30px">Price: {{pro.price}} S.B </p></a>
                                            <div class="links_locat d-flex align-items-center">
                                            
                                                    <img src="{{pro.image.url}}"  style="margin-left:-50px; text-align:center;width:175px;height:200px" class ="contener" alt="">
                                            
                                                                           
                                            </div>
                                        </div>

                                        <div class="apply_now">
                                            <a style ="margin-left:-150px ; margin-top :200px" href="#" class="heart-mark" ><i class=""></i> </a>

                                            <a  style ="margin-left:-32px ; margin-top :380px" href="{% url 'products:update_product' pro.id %}"  class="boxed-btn3 ">Edit</a>

                                           <a style ="margin-left:5px ; margin-top :350px"  href="{% url 'products:delete_product' pro.id %}" class="boxed-btn3">Delete</a>

                                        </div>

                                        {% comment %} <div class="date">
                                            <p>Date Line: </p>
                                        </div> {% endcomment %}
                                    
                                    </div>
                                </div>
                            </div>
                            {% endif %}
                         {% endfor %}

                    
                        </div>

                        
                        {% if products.has_other_pages %}
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>
                                        {% if products.has_previous %}
                                            <li><a href="?page={{products.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in products.paginator.page_range %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if products.has_next %}
                                            <li><a href="?page={{products.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                {% comment %} <div class="col-lg-3 job_details_area " style="padding-top:0px">

                    <div style ="width :250px;margin-top:-1050px;padding-top:0px"class="job_sumary">
                        <div class="summery_header">
                            <h3>Add Product</h3>
                        </div>
                        <div class="job_content">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% bootstrap_form proform %} 
                                {% buttons %}
                                     <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                                {% endbuttons %}     
                            </form>
                        </div>
                    </div>
                </div> {% endcomment %}

            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
{% endblock body %}